apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    run: auth
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 6868
  selector:
    run: auth
